### ISSUE TITLE
SpectralMeasures.jl operators

### ISSUE THREAD

**Issue by marcusdavidwebb** [JuliaArrays/InfiniteArrays.jl#2] opened 2018-03-18 12:56 UTC
Should the operators: `PertToeplitz`, `SymTriToeplitz`, `HessenbergUnitary`, `Unitary`, and others, from SpectralMeasures.jl be eventually moved into this package? 

They are all `Operator`s. I suppose it depends on how much of ApproxFun's `Operator` type will be implemented in this package instead of ApproxFun?

**Comment by dlfivefifty** [comment] 2018-03-18 13:00
This package should have no operators and no spaces, only infinite matrices. 

That said, all those examples you listed are actually infinite matrices and should be here: there will definitely be an `InfToeplitz` at some point, with convenience constructor 
```julia
   diagm(InfRepeated(1)) + diagm(InfRepeated(2),2) # creates InfToeplitz([1], [1,0,2])
```

**Comment by dlfivefifty** [comment] 2018-03-18 13:03
`PertToeplitz` will probably be `PlusInfMatrix{Tuple{<:PaddedInfMatrix,<:InfToeplitz}}}` and in the tridiagonal case `PlusInfMatrix{Tuple{<:PaddedInfMatrix{<:SymTridiagonal},<:InfSymTriToeplitz}`.

`PlusInfMatrix` should support both vector and tuple arguments for this.

**Comment by marcusdavidwebb** [comment] 2018-03-18 13:04
I suppose that PertToeplitz will not be necessary then, because it will just be a PlusInfMatrix of Toeplitz and low rank.

**Comment by dlfivefifty** [comment] 2018-03-18 13:19
While this package should not have a notion of "Operator" or "Space", I think `Operator` might become an interface instead of a type, and then in ApproxFun (or wherever) something can be both an `InfMatrix` or even `AbstractMatrix` and an operator at the same time.  For example, 
```julia
# In ApproxFun.jl
domainspace(A::Union{AbstractMatrix,InfMatrix}) = SequenceSpace(size(A,1))
rangespace(A::Union{AbstractMatrix,InfMatrix}) = SequenceSpace(size(A,2))
```

This has the benefit that mathematically confused notation like `D = Derivative(Chebyshev()); D[1:10,1:10]` becomes more sensical: `D` is an `InfMatrix` that conforms to the operator interface. `D[1:10,1:10]` is treating it as an `InfMatrix`, not an operator, and therefore returns a matrix.  The operator analogue would be `D[SubSpace(Ultraspherical(1),1:10),SubSpace(Chebyshev(),1:10)]`, That is, `getindex(D, ::Space, ::Space)` is interpreting `D` as an operator, and doing the relevant projections.

**Comment by dlfivefifty** [comment] 2018-03-18 13:21
PS I'm going to try to have `InfArray{T,N} <: AbstractArray{T,N}`. That will require a lot of internal Base overrides to work, and will lead to lots of infinite-loops by accident, but has the benefit that code that expects an `AbstractArray` might happen to work without knowing about an `InfArray`.

**Comment by marcusdavidwebb** [comment] 2018-03-18 13:33
base/abstractarray.jl says:
"""
    AbstractArray{T,N}
Supertype for `N`-dimensional arrays (or array-like types) with elements of type `T`.
[`Array`](@ref) and other types are subtypes of this. See the manual section on the
[`AbstractArray` interface](@ref man-interface-array).
"""
and
"""
    size(A::AbstractArray, [dim...])
Returns a tuple containing the dimensions of `A`. Optionally you can specify the
dimension(s) you want the length of, and get the length of that dimension, or a tuple of the
lengths of dimensions you asked for.
```jldoctest
julia> A = ones(2,3,4);
julia> size(A, 2)
3
julia> size(A,3,2)
(4, 3)
```
"""
Of course an InfArray{T,N} is an AbstractArray{T,N}. It's your fault if you assume the dimensions are finite!

**Comment by dlfivefifty** [comment] 2018-03-18 13:39
Hmm, operator-as-interface is hard for getting + and * right, at least if space promotion is desired...

**Comment by daanhb** [comment] 2018-03-18 14:17
Hopefully at some point in the future we may be able to dispatch on traits... That would do away with the problem of having a joint abstract supertype for dispatch, in addition to implementing the right interface.

**Comment by dlfivefifty** [comment] 2018-03-18 14:20
Traits aren’t really the issue here. The issue is that addition of (Inf)Arrays should always work entrywise. But operators have a motion of compatible spaces, so addition is only entrywise if the bases are the same.

**Comment by daanhb** [comment] 2018-03-18 14:25
Okay I see, it is more involved then, thanks.

**Comment by dlfivefifty** [comment] 2018-03-18 14:26
👍 but since this package is just going to do things entrywise, it’s not a concern here

**Comment by dlfivefifty** [comment] 2018-03-20 11:09
> Of course an InfArray{T,N} is an AbstractArray{T,N}

Here's a crazy idea to make this work with minimal copy-and-pasted code: 
```julia
struct CompactifiedInt <: Integer
   x::Union{Int,Infinity}  # this will be efficient in 0.7 I believe
end

promote_rule(::Type{Infinity},::Type{Int}) = CompactifiedInt
Base.OneTo(::Infinity) = Base.OneTo(CompactifiedInt(∞)) # OneTo only takes an Integer
function indices(A::InfVector)
(Base.OneTo(∞),)
end

view(A, 4:∞) # should work!
```

**Comment by dlfivefifty** [comment] 2018-03-20 12:06
PS I double checked the `Union{Int,Infinity}` is efficient claim, and was pretty impressed by the improvement, though it's still not as fast as just `Int`:
```julia
# 0.6
julia> n = 1_000_000; x = Vector{Int}(n); x .= 1:n; @time sum(x)
  0.000370 seconds (5 allocations: 176 bytes)

julia> n = 1_000_000; x = Vector{Union{Void,Int}}(n); x .= 1:n; @time sum(x)
  0.237785 seconds (5.00 M allocations: 76.332 MiB, 75.87% gc time)
```
```julia
# 0.7
julia> n = 1_000_000; x = Vector{Int}(undef,n); x .= 1:n; @time sum(x)
  0.000576 seconds (5 allocations: 176 bytes)
500000500000

julia> n = 1_000_000; x = Vector{Union{Missing,Int}}(undef,n); x .= 1:n; @time sum(x)
  0.005190 seconds (5 allocations: 176 bytes)
500000500000

**Comment by MikaelSlevinsky** [comment] 2018-03-20 12:34
Neat!

**Comment by dlfivefifty** [comment] 2018-03-22 20:44
Here's another option, which in 0.7 is not too much faster than the `Union` option:
```julia
julia> import Base: +

julia> struct InfInt
              isinf::Bool
              x::Int
              end

julia> +(a::InfInt, b::InfInt) = ifelse(a.isinf || b.isinf, InfInt(true,0), InfInt(false, a.x+b.x))
+ (generic function with 179 methods)

julia> Base.convert(::Type{InfInt}, x::Int) = InfInt(false,x)

julia> n = 1_000_000; x = Vector{InfInt}(undef,n);  x .= 1:n;

julia> @time sum(x)
  0.001780 seconds (5 allocations: 192 bytes)
InfInt(false, 500000500000)
```

**Comment by MikaelSlevinsky** [comment] 2018-03-22 20:52
Is it an InfInt or an ExtendedInt?

Cheers,

Mikael

On Mar 22, 2018, at 3:44 PM, Sheehan Olver <notifications@github.com<mailto:notifications@github.com>> wrote:


Here's another option, which in 0.7 is not too much faster than the Union option:

julia> import Base: +

julia> struct InfInt
              isinf::Bool
              x::Int
              end

julia> +(a::InfInt, b::InfInt) = ifelse(a.isinf || b.isinf, InfInt(true,0), InfInt(false, a.x+b.x))
+ (generic function with 179 methods)

julia> Base.convert(::Type{InfInt}, x::Int) = InfInt(false,x)

julia> n = 1_000_000; x = Vector{InfInt}(undef,n);  x .= 1:n;

julia> @time sum(x)
  0.001780 seconds (5 allocations: 192 bytes)
InfInt(false, 500000500000)

**Comment by marcusdavidwebb** [comment] 2018-03-22 20:54
"Extended" appears to be the common term for such a thing: https://en.wikipedia.org/wiki/Extended_real_number_line

**Comment by dlfivefifty** [comment] 2018-03-23 09:41
`ExtendedInt` would by `Union{OrientedInfinity{Bool}, Int}`: that is, support `±∞`.

Since the main focus is on `indices` (`Base.OneTo(∞)`), `∞` refers to cardinality, and we really want `ExtendedNaturalNumbers`, e.g.,  `Union{UInt, Infinity}`. Of course, for very good reasons (underflow?) we should use `Int` for indices, which would be `Union{Int,Infinity}`. 

Note: as I've coded it up `+∞` is different from `∞`. I think this is correct: limit vs cardinality.

**Comment by dlfivefifty** [comment] 2019-07-29 09:14
Closing this since InfiniteLinearAlgebra.jl (renamed from InfiniteBandedMatrices.jl) has already done most of the proposed.

**Closed by dlfivefifty** 2019-07-29 09:14 UTC
